from django.core.exceptions import ValidationError


def _validator(value):
    """Проверка """



    return value
